# Form implementation generated from reading ui file 'forgotpass.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 400)
        Dialog.setStyleSheet("QLineEdit{\n"
"padding-left:50px;\n"
"background: white;\n"
"border: 1px solid #005F49;\n"
"border-radius: 10px\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #005F49;\n"
"\n"
"}\n"
"QLabel{\n"
"color:#00557F;\n"
"font:bold\n"
"}\n"
"QDialog{\n"
"background-color:#E3F1EE;\n"
"    background-image: url(icon//bg.jpg);\n"
"}\n"
"\n"
"#btn_openregis,#btn_forgotpass{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#btn_openregis:hover,#btn_forgotpass:hover{\n"
"    text-decoration:underline;    \n"
"    color: rgb(0, 85, 127);\n"
"}\n"
"#btn_confirm,#btn_confirmotp,#btn_confirmpass{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(173, 216, 230, 255), stop:1 rgba(170, 225, 255, 255));\n"
"    border-radius: 15px;\n"
"    color:#00557F;\n"
"    font-weight:bold\n"
"}\n"
"#btn_confirm:hover,#btn_confirmotp:hover,#btn_confirmpass:hover{\n"
"    background-color: #00557F;\n"
"    border-radius: 15px; \n"
"    cursor: pointer;\n"
"    color: white;\n"
"}")
        self.btn_confirm = QtWidgets.QPushButton(parent=Dialog)
        self.btn_confirm.setGeometry(QtCore.QRect(210, 340, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_confirm.setFont(font)
        self.btn_confirm.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_confirm.setMouseTracking(False)
        self.btn_confirm.setStyleSheet("")
        self.btn_confirm.setObjectName("btn_confirm")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(150, 200, 30, 30))
        self.label_2.setStyleSheet("image: url(icon//user.png);\n"
"border-radius: 10px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.txt_email = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_email.setGeometry(QtCore.QRect(140, 250, 350, 50))
        self.txt_email.setMinimumSize(QtCore.QSize(200, 48))
        self.txt_email.setMaximumSize(QtCore.QSize(500, 500))
        self.txt_email.setObjectName("txt_email")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 0, 200, 171))
        self.label_3.setStyleSheet("image: url(icon//fg.png);\n"
"border-radius: 10px;")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(240, 140, 161, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.txt_username = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_username.setGeometry(QtCore.QRect(140, 190, 350, 50))
        self.txt_username.setMinimumSize(QtCore.QSize(200, 48))
        self.txt_username.setMaximumSize(QtCore.QSize(500, 500))
        self.txt_username.setObjectName("txt_username")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(150, 260, 30, 30))
        self.label_5.setStyleSheet("image: url(icon//icons8-email-100.png);\n"
"border-radius: 10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.txt_otp = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_otp.setGeometry(QtCore.QRect(140, 220, 350, 50))
        self.txt_otp.setMinimumSize(QtCore.QSize(200, 48))
        self.txt_otp.setMaximumSize(QtCore.QSize(500, 500))
        self.txt_otp.setObjectName("txt_otp")
        self.btn_hiderepass = QtWidgets.QPushButton(parent=Dialog)
        self.btn_hiderepass.setGeometry(QtCore.QRect(490, 270, 45, 45))
        self.btn_hiderepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hiderepass.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_hiderepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hiderepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hiderepass.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon//hidepass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_hiderepass.setIcon(icon)
        self.btn_hiderepass.setObjectName("btn_hiderepass")
        self.btn_hidepass = QtWidgets.QPushButton(parent=Dialog)
        self.btn_hidepass.setGeometry(QtCore.QRect(490, 190, 45, 45))
        self.btn_hidepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hidepass.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_hidepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hidepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hidepass.setText("")
        self.btn_hidepass.setIcon(icon)
        self.btn_hidepass.setObjectName("btn_hidepass")
        self.txt_password = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_password.setGeometry(QtCore.QRect(90, 185, 450, 50))
        self.txt_password.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_password.setMaximumSize(QtCore.QSize(450, 50))
        self.txt_password.setObjectName("txt_password")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(100, 195, 30, 30))
        self.label_6.setStyleSheet("image: url(icon//password.png);\n"
"background-color: none;\n"
"border-radius: 10px")
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=Dialog)
        self.label_7.setGeometry(QtCore.QRect(100, 275, 30, 30))
        self.label_7.setStyleSheet("image: url(icon//password.png);\n"
"background-color: none;\n"
"border-radius: 10px")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.txt_repassword = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_repassword.setGeometry(QtCore.QRect(90, 265, 450, 50))
        self.txt_repassword.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_repassword.setMaximumSize(QtCore.QSize(450, 50))
        self.txt_repassword.setObjectName("txt_repassword")
        self.btn_confirmotp = QtWidgets.QPushButton(parent=Dialog)
        self.btn_confirmotp.setGeometry(QtCore.QRect(210, 340, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_confirmotp.setFont(font)
        self.btn_confirmotp.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_confirmotp.setMouseTracking(False)
        self.btn_confirmotp.setStyleSheet("")
        self.btn_confirmotp.setObjectName("btn_confirmotp")
        self.btn_confirmpass = QtWidgets.QPushButton(parent=Dialog)
        self.btn_confirmpass.setGeometry(QtCore.QRect(210, 340, 200, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.btn_confirmpass.setFont(font)
        self.btn_confirmpass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_confirmpass.setMouseTracking(False)
        self.btn_confirmpass.setStyleSheet("")
        self.btn_confirmpass.setObjectName("btn_confirmpass")
        self.txt_password.raise_()
        self.txt_repassword.raise_()
        self.txt_username.raise_()
        self.btn_confirm.raise_()
        self.label_2.raise_()
        self.txt_email.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.txt_otp.raise_()
        self.btn_hiderepass.raise_()
        self.btn_hidepass.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.btn_confirmotp.raise_()
        self.btn_confirmpass.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Màn hình đăng nhập"))
        self.btn_confirm.setText(_translate("Dialog", "Gửi OTP"))
        self.txt_email.setPlaceholderText(_translate("Dialog", "Mời bạn nhập email"))
        self.label_4.setText(_translate("Dialog", "Quên mật khẩu"))
        self.txt_username.setPlaceholderText(_translate("Dialog", "Mời bạn nhập tên tài khoản"))
        self.txt_otp.setPlaceholderText(_translate("Dialog", "Nhập otp"))
        self.txt_password.setPlaceholderText(_translate("Dialog", "Tạo mật khẩu"))
        self.txt_repassword.setPlaceholderText(_translate("Dialog", "Xác nhận mật khẩu"))
        self.btn_confirmotp.setText(_translate("Dialog", "Xác nhận"))
        self.btn_confirmpass.setText(_translate("Dialog", "Cập nhật mật khẩu"))
