# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 350)
        Dialog.setStyleSheet("QLineEdit{\n"
"padding:8px;\n"
"background: white;\n"
"border: 1px solid #005F49;\n"
"border-radius: 10px\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #005F49;\n"
"}\n"
"QLabel{\n"
"color:#00557F;\n"
"font:bold\n"
"}\n"
"QDialog{\n"
"background-color:#E3F1EE;\n"
"background-image: url(/icon/bg.jpg)\n"
"}\n"
"\n"
"#btn_signup{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(173, 216, 230, 255), stop:1 rgba(170, 225, 255, 255));\n"
"    border-radius: 15px;\n"
"    color: rgb(245, 245, 235);\n"
"}\n"
"#btn_signup:hover{\n"
"    background-color: rgba(200, 216, 230, 255);\n"
"    cursor: pointer;\n"
"    color: black;\n"
"}")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(500, 10, 201, 41))
        self.label_4.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align: center")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.btn_signup = QtWidgets.QPushButton(parent=Dialog)
        self.btn_signup.setGeometry(QtCore.QRect(470, 290, 250, 35))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_signup.setFont(font)
        self.btn_signup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_signup.setStyleSheet("")
        self.btn_signup.setObjectName("btn_signup")
        self.txt_username = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_username.setGeometry(QtCore.QRect(420, 60, 350, 50))
        self.txt_username.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_username.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_username.setObjectName("txt_username")
        self.btn_hidepass = QtWidgets.QPushButton(parent=Dialog)
        self.btn_hidepass.setGeometry(QtCore.QRect(720, 135, 45, 45))
        self.btn_hidepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hidepass.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_hidepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hidepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hidepass.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon/hidepass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_hidepass.setIcon(icon)
        self.btn_hidepass.setObjectName("btn_hidepass")
        self.txt_repassword = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_repassword.setGeometry(QtCore.QRect(420, 210, 350, 50))
        self.txt_repassword.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_repassword.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_repassword.setObjectName("txt_repassword")
        self.btn_hiderepass = QtWidgets.QPushButton(parent=Dialog)
        self.btn_hiderepass.setGeometry(QtCore.QRect(720, 215, 45, 45))
        self.btn_hiderepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hiderepass.setMaximumSize(QtCore.QSize(50, 50))
        self.btn_hiderepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hiderepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hiderepass.setText("")
        self.btn_hiderepass.setIcon(icon)
        self.btn_hiderepass.setObjectName("btn_hiderepass")
        self.txt_password = QtWidgets.QLineEdit(parent=Dialog)
        self.txt_password.setGeometry(QtCore.QRect(420, 130, 350, 50))
        self.txt_password.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_password.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_password.setObjectName("txt_password")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(0, 0, 351, 351))
        self.label.setStyleSheet("image: url(icon/login.jpg);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(370, 60, 45, 45))
        self.label_5.setStyleSheet("image: url(icon/user.png);\n"
"border-radius: 10px;")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(370, 130, 45, 45))
        self.label_2.setStyleSheet("image: url(icon/password.png);\n"
"background-color: none;\n"
"border-radius: 10px")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(370, 210, 45, 45))
        self.label_3.setStyleSheet("image: url(icon/password.png);\n"
"background-color: none;\n"
"border-radius: 10px")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.txt_password.raise_()
        self.label_4.raise_()
        self.btn_signup.raise_()
        self.txt_username.raise_()
        self.btn_hidepass.raise_()
        self.txt_repassword.raise_()
        self.btn_hiderepass.raise_()
        self.label.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.label_3.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Màn hình đăng ký tài khoản"))
        self.label_4.setText(_translate("Dialog", "Đăng ký tài khoản"))
        self.btn_signup.setText(_translate("Dialog", "Đăng ký"))
        self.txt_username.setPlaceholderText(_translate("Dialog", "Tạo tài khoản"))
        self.txt_repassword.setPlaceholderText(_translate("Dialog", "Xác nhận mật khẩu"))
        self.txt_password.setPlaceholderText(_translate("Dialog", "Tạo mật khẩu"))
