# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(600, 350)
        Dialog.setStyleSheet("QLineEdit{\n"
"padding:8px;\n"
"background: white;\n"
"border: 1px solid #005F49;\n"
"border-radius: 10px\n"
"}\n"
"QLineEdit:focus{\n"
"border: 2px solid #005F49;\n"
"}\n"
"QLabel{\n"
"color:#00557F;\n"
"font:bold\n"
"}\n"
"QDialog{\n"
"background-color:#E3F1EE;\n"
"background-image: url(icon//bg.jpg)\n"
"}\n"
"\n"
"#btn_regis{\n"
"    background-color: rgba(255, 255, 255, 0);\n"
"}\n"
"#btn_regis:hover{\n"
"    text-decoration:underline;    \n"
"    color: rgb(0, 85, 127);\n"
"}")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 600, 50))
        self.label_4.setMinimumSize(QtCore.QSize(600, 50))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("text-align: center")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setIndent(-1)
        self.label_4.setObjectName("label_4")
        self.btn_signup = QtWidgets.QPushButton(parent=Dialog)
        self.btn_signup.setGeometry(QtCore.QRect(230, 270, 120, 35))
        self.btn_signup.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_signup.setStyleSheet("font:bold;\n"
"border-radius: 5px")
        self.btn_signup.setObjectName("btn_signup")
        self.layoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 70, 572, 172))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.txt_username = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txt_username.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_username.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_username.setObjectName("txt_username")
        self.horizontalLayout.addWidget(self.txt_username)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setMinimumSize(QtCore.QSize(40, 40))
        self.label_3.setMaximumSize(QtCore.QSize(40, 40))
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.txt_password = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txt_password.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_password.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_password.setObjectName("txt_password")
        self.horizontalLayout_3.addWidget(self.txt_password)
        self.btn_hidepass = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_hidepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hidepass.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_hidepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hidepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hidepass.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon//hidepass.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_hidepass.setIcon(icon)
        self.btn_hidepass.setObjectName("btn_hidepass")
        self.horizontalLayout_3.addWidget(self.btn_hidepass)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.txt_repassword = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.txt_repassword.setMinimumSize(QtCore.QSize(350, 50))
        self.txt_repassword.setMaximumSize(QtCore.QSize(350, 50))
        self.txt_repassword.setObjectName("txt_repassword")
        self.horizontalLayout_2.addWidget(self.txt_repassword)
        self.btn_hiderepass = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_hiderepass.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_hiderepass.setMaximumSize(QtCore.QSize(40, 40))
        self.btn_hiderepass.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_hiderepass.setStyleSheet("background-color: rgba(255, 255, 255, 0);")
        self.btn_hiderepass.setText("")
        self.btn_hiderepass.setIcon(icon)
        self.btn_hiderepass.setObjectName("btn_hiderepass")
        self.horizontalLayout_2.addWidget(self.btn_hiderepass)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Màn hình đăng ký tài khoản"))
        self.label_4.setText(_translate("Dialog", "Đăng ký tài khoản"))
        self.btn_signup.setText(_translate("Dialog", "Đăng ký"))
        self.label.setText(_translate("Dialog", "Tài khoản "))
        self.txt_username.setPlaceholderText(_translate("Dialog", "Tạo tài khoản"))
        self.label_5.setText(_translate("Dialog", "Mật khẩu"))
        self.txt_password.setPlaceholderText(_translate("Dialog", "Tạo mật khẩu"))
        self.label_2.setText(_translate("Dialog", "Xác nhận mật khẩu"))
        self.txt_repassword.setPlaceholderText(_translate("Dialog", "Xác nhận mật khẩu"))
